name: Tests

on:
  push:
    # This should disable running the workflow on tags, according to the
    # on.<push|pull_request>.<branches|tags> GitHub Actions docs.
    branches:
      - "*"
  pull_request:

concurrency:
  # Cancel older requests of the same workflow in the same branch.
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    strategy:
      fail-fast: false
      matrix:
        pg: [16, 15, 14, 13, 12, 11, 10]
    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }} libgmp-dev
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test on PostgreSQL ${{ matrix.pg }}
        run: pg-build-test
